ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# ws_dir = Pathname.new(__dir__)
# ws_dir = ws_dir.parent until
#   File.exist?("#{ws_dir}/node_modules/react-native-test-app/test_app.rb") ||
#   ws_dir.expand_path.to_s == '/'
# require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"

# workspace 'RtnDevConsoleExample.xcworkspace'

# use_test_app! :hermes_enabled => true

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_modular_headers!

target 'RtnDevConsoleExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Cocoapods doesn't use a podspec's spec.source when the podfile dep uses :git/:path
  # See: https://github.com/CocoaPods/CocoaPods/issues/11255#issuecomment-1475314728
  pod 'CSSH', :podspec => 'https://github.com/TheTekton337/Libssh2Prebuild/raw/master/CSSH.podspec'

  pod 'CSwiftSH', :git => 'https://github.com/TheTekton337/SwiftSH.git', :branch =>'rtn-dev-console'
  pod 'SwiftSH', :git => 'https://github.com/TheTekton337/SwiftSH.git', :branch =>'rtn-dev-console'
  
  pod 'SwiftTerm', :git => 'https://github.com/TheTekton337/SwiftTerm.git', :branch =>'rtn-dev-console'

  target 'RtnDevConsoleExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
